### ISSUE TITLE
Failed to install tensorflow.js

### ISSUE THREAD

**Issue by Emporea** [marcelklehr/recognize#113]
```
[no app in context] Error: Exception while executing repair step Install dependencies

POST /settings/apps/enable
from x.x.x.x by emporea at 2021-11-08T18:07:58+00:00

{"reqId":"BnENWfbUrPJhQBKuoOuJ","level":3,"time":"2021-11-08T18:07:58+00:00","remoteAddr":"x.x.x.x","user":"emporea","app":"no app in context","method":"POST","url":"/settings/apps/enable","message":"Exception while executing repair step Install dependencies","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0","version":"22.2.0.2","exception":{"Exception":"Exception","Message":"Failed to install Tensorflow.js: CPU-linux-3.8.0.tar.gz\nnode-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build\ninternal/modules/cjs/loader.js:892\n  throw err;\n  ^\n\nError: Cannot find module 'wide-align'\nRequire stack:\n- /var/www/html/custom_apps/recognize/node_modules/gauge/render-template.js\n- /var/www/html/custom_apps/recognize/node_modules/gauge/plumbing.js\n- /var/www/html/custom_apps/recognize/node_modules/gauge/index.js\n- /var/www/html/custom_apps/recognize/node_modules/npmlog/log.js\n- /var/www/html/custom_apps/recognize/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js\n- /var/www/html/custom_apps/recognize/node_modules/@mapbox/node-pre-gyp/lib/main.js\n- /var/www/html/custom_apps/recognize/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:745:27)\n    at Module.require (internal/modules/cjs/loader.js:961:19)\n    at require (internal/modules/cjs/helpers.js:92:18)\n    at Object.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/gauge/render-template.js:2:13)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n    at Module.load (internal/modules/cjs/loader.js:937:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:778:12)\n    at Module.require (internal/modules/cjs/loader.js:961:19) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/var/www/html/custom_apps/recognize/node_modules/gauge/render-template.js',\n    '/var/www/html/custom_apps/recognize/node_modules/gauge/plumbing.js',\n    '/var/www/html/custom_apps/recognize/node_modules/gauge/index.js',\n    '/var/www/html/custom_apps/recognize/node_modules/npmlog/log.js',\n    '/var/www/html/custom_apps/recognize/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js',\n    '/var/www/html/custom_apps/recognize/node_modules/@mapbox/node-pre-gyp/lib/main.js',\n    '/var/www/html/custom_apps/recognize/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp'\n  ]\n}","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php","line":83,"function":"runTfjsInstall","class":"OCA\\Recognize\\Migration\\InstallDeps","type":"->","args":["/var/www/html/custom_apps/recognize/bin//node"]},{"file":"/var/www/html/lib/private/Repair.php","line":123,"function":"run","class":"OCA\\Recognize\\Migration\\InstallDeps","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":1059,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"/var/www/html/lib/private/Installer.php","line":166,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["recognize",{"step":"OCA\\Recognize\\Migration\\InstallDeps"}]},{"file":"/var/www/html/apps/settings/lib/Controller/AppSettingsController.php","line":447,"function":"installApp","class":"OC\\Installer","type":"->","args":["recognize"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["recognize"],[]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php","Line":114,"CustomMessage":"Exception while executing repair step Install dependencies"},"id":"6189682a388aa"}
```

I get this error after i hit at manual classify. Its still working but i guess that means its slower. What can / should I do?

Nextcloud: 22.2
Dockerimage: fpm
RAM: 32GB

**Comment by marcelklehr** [comment]
This is curious. Does this still happen with the latest version?

**Comment by gjwgit** [comment]
I am getting this issue with Ubuntu 23.04, Nextcloud 25.0.6snap1, Recognize 3.8.0 -  reopening this issue?

```
Failed to install Tensorflow.js: CPU-linux-4.2.0.tar.gz\n* Downloading libtensorflow

https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.9.1.tar.gz\n\n*

Building TensorFlow Node.js bindings\nnode-pre-gyp install failed with
error: 

Error: Command failed node-pre-gyp install --fallback-to-build

/usr/bin/env: 'node': No such file or directory
```

After a `sudo nextcloud:occ memories:index` the server started going
in and out of maintenance mode. The `memories:index` command gave all
indications that it succeeded (except for a `Setting locale failed`
message). I then tried `sudo nextcloud.occ maintenance:repair` and
that was okay until:

```
[...]
 - Install dependencies
     - ERROR: Failed to install Tensorflow.js: CPU-linux-4.2.0.tar.gz
  * Downloading libtensorflow
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.9.1.tar.gz

 * Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
/usr/bin/env: 'node': No such file or directory
[...]
```
On reviewing the log file:

```bash
sudo most /var/snap/nextcloud/current/logs/nextcloud.log
```

there were ongoing entries every 50 seconds that began after the above
commands (it was not prevalent prior):

```console
  {"reqId":"Vwrlrb3tMUAyDlAUJVHV", "level":3,
  "time":"2023-06-04T10:26:23+00:00", "remoteAddr":"", "user":"--",
  "app":"recognize", "method":"", "url":"--", "message":"Failed
  to install Tensorflow.js: CPU-linux-4.2.0.tar.gz\n* Downloading
  libtensorflow\nhttps://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.9.1.tar.gz\n\n*
  Building TensorFlow Node.js bindings\nnode-pre-gyp install failed
  with error: Error: Command failed node-pre-gyp install
  --fallback-to-build\n/usr/bin/env: 'node': No such file or
  directory", "userAgent":"--", "version":"25.0.6.1", "data":{"app":"recognize"}}
```

This caused the server to be in maintenance mode every time this
attempted install was being undertaken. This was resolved by disabling
recognize 3.8.0.

```bash
sudo nextcloud.occ app:disable recognize
```

A manual reinstall did not succeed installing Tensorflow however the
repeated attempts every 50 seconds did not start up again. Perhaps
that needs a `sudo nextcloud.occ maintenance:repair` to get that going.

```
$ sudo nextcloud.occ app:remove recognize
$ sudo nextcloud.occ app:install recognize
```
