### ISSUE TITLE
Classifier process output: RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range

### ISSUE THREAD

**Issue by oiwrhnoieajv** [marcelklehr/recognize#148]
**Describe the bug**
After finding/searching files, the process will freeze at
       ```
Running array (
            0 => '/var/www/nextcloud/apps/recognize/bin//node',
            1 => '/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
            2 => '-',
             )
```
before the following Error occures

    Classifier process output: RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <=                                   1073741823. Received 1097234836
        at validateOffset (buffer.js:111:3)
        at Function.concat (buffer.js:565:5)
        at PassThrough.stream.getBufferedValue (/var/www/nextcloud/apps/recognize/node_modules/get-stream/buffer-stream.js:45:26)
        at /var/www/nextcloud/apps/recognize/node_modules/get-stream/index.js:44:23
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Promise.all (index 0)
        at async main (/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js:82:3) {
      code: 'ERR_OUT_OF_RANGE'
    }

    Classifier process output: RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <=     1073741823. Received 1097234836
        at validateOffset (buffer.js:111:3)
        at Function.concat (buffer.js:565:5)
        at PassThrough.stream.getBufferedValue (/var/www/nextcloud/apps/recognize/node_modules/get-stream/buffer-stream.js:45:26)
        at /var/www/nextcloud/apps/recognize/node_modules/get-stream/index.js:44:23
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Promise.all (index 0)
        at async main (/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js:82:3) {
      code: 'ERR_OUT_OF_RANGE'
    }

Failed to classify images
Classifier process error

**To Reproduce**

1. Go to shell 
2. run /occ preview:pre-generate 
3. Wait for processing

**Expected behavior**
Tagging all images

**Recognize (please complete the following information):**
 - Tensorflow plain mode: JavaScript mode enabled
 - Enabled modes: face, object, landmark

**Server (please complete the following information):**
 - Nextcloud: [e.g. 21.0.4]
- 4 GB RAM on Rasberry Pi 4 ( Linux 5.10.92)
- PHP 8.0

**Comment by marcelklehr** [comment]
Which version of recognize is this?

**Comment by marcelklehr** [comment]
Off, this seems to be some [limitation of the download library](https://github.com/sindresorhus/get-stream/issues/48) for download sizes more than 1GiB :/

**Comment by spicemint** [comment]
same error here on pi4, nextcloud 23.0.2, Apache/2.4.38, PHP 7.3.31-1~deb10u1, 

  10711 => '/var/data/admin/files/Video/Wyjazd.Integracyjny 2011 DVDRip.XviD-BiDA FILM POLSKI Upload zaloga TC/GIf....png',
)
Running array (
  0 => '/var/www/nextcloud/apps/recognize/bin//node',
  1 => '/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
0

Classifier process output: RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <= 1073741823. Received 1097235711
    at validateOffset (buffer.js:111:3)
    at Function.concat (buffer.js:565:5)
    at PassThrough.stream.getBufferedValue (/var/www/nextcloud/apps/recognize/node_modules/get-stream/buffer-stream.js:45:26)
    at /var/www/nextcloud/apps/recognize/node_modules/get-stream/index.js:44:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async exports.downloadAll (/var/www/nextcloud/apps/recognize/src/model-manager.js:8:2)
    at async main (/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js:82:3) {
  code: 'ERR_OUT_OF_RANGE'
}

Classifier process output: RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <= 1073741823. Received 1097235711
    at validateOffset (buffer.js:111:3)
    at Function.concat (buffer.js:565:5)
    at PassThrough.stream.getBufferedValue (/var/www/nextcloud/apps/recognize/node_modules/get-stream/buffer-stream.js:45:26)
    at /var/www/nextcloud/apps/recognize/node_modules/get-stream/index.js:44:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at async exports.downloadAll (/var/www/nextcloud/apps/recognize/src/model-manager.js:8:2)
    at async main (/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js:82:3) {
  code: 'ERR_OUT_OF_RANGE'
}

Failed to classify images

**Comment by droogi** [comment]
same error, want to stay updated

**Comment by b4lrog** [comment]
In the mean time.
A temporary workaround is to manually download the library : wget https://github.com/marcelklehr/recognize/archive/refs/tags/v2.2.1.tar.gz (the number is the version number in the package.json file)
Extract the files and copy or link to the "models" folder  <next cloud root>/apps/recognize/model.
The process then does not try to download the file.

**Comment by marcelklehr** [comment]
In v3 you can now download models using an occ command, which should be a simple workaround.
