### ISSUE TITLE
'GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/recognize#207]
**Describe the bug**

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[...]
Classifier process error
Failed to classify images
```

**To Reproduce**
1. Install and enable all options

**Expected behavior**
Classifier runs

**Recognize (please complete the following information):**
 - JS-only mode: No
 - Enabled modes: all

**Server (please complete the following information):**
 - Nextcloud: 22
 - OS: official nextcloud docker
 - Processor Architecture: x86

**Comment by marcelklehr** [comment]
WASM mode resolves this, but I'd like native speed of course

**Comment by derritter88** [comment]
Same here.

**Comment by alfwro13** [comment]
same here on up-to-date Debian 11 and Nextcloud 23.0.4

**Comment by derritter88** [comment]
Thanks @marcelklehr !
