### ISSUE TITLE
Process stops (TypeError) after a few hours

### ISSUE THREAD

**Issue by b3nis** [marcelklehr/recognize#214]
The processes is running fine for a few hours - then getting this error:

```
Result for 2017-08-06 at 18.16.14.jpg = ["Sweden"]
Result for 2017-08-06 at 18.16.30.jpg = ["Sweden"]
Result for 2017-08-06 at 18.16.32.jpg = ["Sweden"]
Result for 2017-08-06 at 22.47.08.jpg = [null]
An unhandled exception has been thrown:
TypeError: OC\SystemTag\SystemTagManager::getTag(): Argument #1 ($tagName) must be of type string, null given, called in /var/www/html/custom_apps/recognize/lib/Service/TagManager.php on line 25 and defined in /var/www/html/lib/private/SystemTag/SystemTagManager.php:174
Stack trace:
#0 /var/www/html/custom_apps/recognize/lib/Service/TagManager.php(25): OC\SystemTag\SystemTagManager->getTag(NULL, true, true)
#1 /var/www/html/custom_apps/recognize/lib/Service/TagManager.php(43): OCA\Recognize\Service\TagManager->getTag(NULL)
#2 [internal function]: OCA\Recognize\Service\TagManager->OCA\Recognize\Service\{closure}(NULL)
#3 /var/www/html/custom_apps/recognize/lib/Service/TagManager.php(42): array_map(Object(Closure), Array)
#4 /var/www/html/custom_apps/recognize/lib/Classifiers/Images/GeoClassifier.php(84): OCA\Recognize\Service\TagManager->assignTags(104501, Array)
#5 /var/www/html/custom_apps/recognize/lib/Service/ClassifyImagesService.php(86): OCA\Recognize\Classifiers\Images\GeoClassifier->classify(Array)
#6 /var/www/html/custom_apps/recognize/lib/Command/ClassifyImages.php(59): OCA\Recognize\Service\ClassifyImagesService->run('benjamin', 500)
#7 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Recognize\Command\ClassifyImages->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Recognize\Command\ClassifyImages), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/console.php(99): OC\Console\Application->run()
#13 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

Running latest version, 2.0.1 on NC 22.2.7 (Docker).

**Comment by marcelklehr** [comment]
This is the geo tagging component. For now disabling geo tagging should fix things. I will look into the geo tagging component to fix the bug.

**Comment by b3nis** [comment]
Thanks for the quick reply!

**Comment by b3nis** [comment]
Thanks for fixing it so quickly @marcelklehr 

Can I rerun the geotag part without having to rerun everything?

**Comment by marcelklehr** [comment]
Not currently, the next version will incrementally rerun everything on a new release without removing all tags beforehand.

**Comment by b3nis** [comment]
That's it - I am now donating to this project, amazing stuff.

**Comment by kc9jud** [comment]
@marcelklehr has 6f78be7 been released yet? I just got this error, but it looks like it may already be fixed in the next release?

**Comment by marcelklehr** [comment]
The fix hasn't been released yet

**Comment by kc9jud** [comment]
You all are getting good -- you fix the issues before I can even open them here!
