### ISSUE TITLE
Cannot find module 'execa'

### ISSUE THREAD

**Issue by d4f0** [marcelklehr/recognize#231]
**Describe the bug**
Video recognition gives the following error:
`Classifier process output: internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'execa'
Require stack:
- /var/www/nextcloud/apps/recognize/src/movinet/MovinetModel.js
- /var/www/nextcloud/apps/recognize/src/classifier_movinet.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/src/movinet/MovinetModel.js:25:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/nextcloud/apps/recognize/src/movinet/MovinetModel.js',
    '/var/www/nextcloud/apps/recognize/src/classifier_movinet.js'
  ]
}`

**To Reproduce**
Install recognize and execute occ recognize:classify-video

**Expected behavior**
Classify video

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: face recognition, location tagging, object detection, landmark recognition, human action recognition

**Server (please complete the following information):**
 - Nextcloud: 23.0.5
 - OS: Debian LXC
 - RAM: 6GB
 - Processor Architecture: x86

**Comment by lowrents** [comment]
Hi, 
I got the same error using `occ recognize:classify-music`

```
sudo apt install npm
npm install execa
npm install node-fetch@2.6.6
```
fixed this, but there was an other error afterwards, which was cause by: `/var/www/html/custom_apps/recognize/src/musicnn/MusicnnModel.js:23:15`
not sure if this or a similar will occur while indexing the videos. However I could fixed this issue by replace `require()`by `import()`

perhaps this helps
cheers

**Comment by marcelklehr** [comment]
Sorry for the delay. Will be fixed in the next release :)

**Comment by d4f0** [comment]
No problem. Thank you very much for dedicating your time to fix it.
