### ISSUE TITLE
A few errors when running v1.5.2 on NCv22

### ISSUE THREAD

**Issue by KruyKaze** [marcelklehr/recognize#51]
Hello I updated to the new version today and I got a lot of errors : 

`[recognize] Warning: Classifier process output: 2021-08-17 14:00:52.092611: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-08-17 14:00:52.131145: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-17 14:00:52.132132: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-08-17 14:00:52.213808: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-08-17 14:00:52.213845: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (arch): /proc/driver/nvidia/version does not exist
internal/fs/utils.js:314
    throw err;
    ^

Error: EAGAIN: resource temporarily unavailable, read
    at Object.readSync (fs.js:614:3)
    at tryReadSync (fs.js:383:20)
    at Object.readFileSync (fs.js:420:19)
    at Object.<anonymous> (/usr/share/webapps/nextcloud/apps/recognize/src/classifier_faces.js:12:23)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -11,
  syscall: 'read',
  code: 'EAGAIN'
}

by REDACTED at 2021-08-17T20:00:52+00:00

__________________________________

[PHP] Error: fwrite(): Write of 1913948 bytes failed with errno=32 Broken pipe at /usr/share/webapps/nextcloud/3rdparty/symfony/process/Pipes/AbstractPipes.php#128

by REDACTED at 2021-08-17T20:00:52+00:00

---------------------------------

[PHP] Error: file_get_contents(VALUE=uri:https://REDACTED.duckdns.org/remote.php/dav/addressbooks/system/system/system/Database:REDACTED.vcf?photo): Failed to open stream: No such file or directory at /usr/share/webapps/nextcloud/apps/recognize/lib/Service/ReferenceFacesFinderService.php#70

by REDACTED at 2021-08-17T20:00:51+00:00

`
I am running PHP  8.0.9   mysql 10.5.10 
I appreciate the help!

**Comment by marcelklehr** [comment]
Hi, sorry for your troubles and thank you for reporting! The new version seems to have some toothing problems. I'll investigate and release patches soon.

**Comment by KruyKaze** [comment]
Great thank you

**Comment by KruyKaze** [comment]
Thank you for the update, unfortunately when I ran the new version v1.5.3 , I get these errors:


`[recognize] Warning: Classifier process output: internal/modules/cjs/loader.js:1131
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/share/webapps/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/lib/napi-v8/../../deps/lib/libtensorflow_framework.so.2: file too short
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/webapps/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)


by REDACTED at 2021-08-20T18:45:50+00:00


-----------------------------------

[PHP] Error: fwrite(): Write of 88410 bytes failed with errno=32 Broken pipe at /usr/share/webapps/nextcloud/3rdparty/symfony/process/Pipes/AbstractPipes.php#128

by REDACTED at 2021-08-20T18:45:50+00:00


----------------------------------

[PHP] Error: file_get_contents(VALUE=uri:https://REDACTED.duckdns.org/remote.php/dav/addressbooks/system/system/system/Database:REDACTED.vcf?photo): Failed to open stream: No such file or directory at /usr/share/webapps/nextcloud/apps/recognize/lib/Service/ReferenceFacesFinderService.php#74

by REDACTED at 2021-08-20T18:45:50+00:00

---------------------------------

[PHP] Error: file_get_contents(VALUE=uri:https://REDACTED.duckdns.org/remote.php/dav/addressbooks/system/system/system/Database:REDACTED.vcf?photo): Failed to open stream: No such file or directory at /usr/share/webapps/nextcloud/apps/recognize/lib/Service/ReferenceFacesFinderService.php#74

by REDACTED at 2021-08-20T18:45:50+00:00

`


I didn't want to open a new issue to have some continuity. Please let me know if you need other details. And thanks in advance.

**Comment by marcelklehr** [comment]
These should be fixed with the latest commit, I'll do a new release soon-ish.

**Comment by marcelklehr** [comment]
Here we go: https://github.com/marcelklehr/recognize/releases/tag/v1.5.4-beta.1

It's a pre-release, so it's not on the appstore, yet.

**Comment by KruyKaze** [comment]
I'll try the actual release as soon as it's available.
Thanks

**Comment by KruyKaze** [comment]
I see v1.5.4 was released but for some reason, NC will not download it. I
rebooted and removed Recognize and re-added it. But still only shows 1.5.3

**Comment by marcelklehr** [comment]
Yeah, 1.5.4 was too large for the appstore :see_no_evil: I've reduced the bundle size further with v1.5.5 and it's available on the appstore now.

**Comment by KruyKaze** [comment]
Here are the errors for 1.5.7:

`[recognize] Warning: Classifier process output: internal/modules/cjs/loader.js:1131
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/share/webapps/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow_framework.so.2: file too short
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/share/webapps/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)


at 2021-08-23T18:59:05+00:00


--------------------------


[PHP] Error: fwrite(): Write of 1983553 bytes failed with errno=32 Broken pipe at /usr/share/webapps/nextcloud/3rdparty/symfony/process/Pipes/AbstractPipes.php#128

at 2021-08-23T18:59:05+00:00`

Thank you

**Comment by KruyKaze** [comment]
Note that I get that when I do the initial "occ recognize:classify" . Should I skip doing that?

**Comment by marcelklehr** [comment]
Yep, it's broken, too. I think the only way out is to tackle something I've been trying to avoid: see #52
