### ISSUE TITLE
libtnsorflow.so.2 cannot open shared object file

### ISSUE THREAD

**Issue by vanderheyde** [marcelklehr/recognize#62]
Hi!

I Installed recognize via the nextcloud (v21.0.4) appstore but it did not recognize any images. There were no errors, though and I didn't look much into it at the time.

Today, I upgraded via the nextcloud app to v1.5.5 and receive the following error:

> $ sudo -u www-data php occ recognize:classify
> Classifying photos of user abcdefgh
> Failed to classify images
> Classifier process error

Nextcloud logs shows the following:

```
[recognize] Warning: Classifier process output: internal/modules/cjs/loader.js:1131
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libtensorflow.so.2: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)

```

at 2021-08-23T14:11:55+00:00

**Comment by jakobroehrl** [comment]
duplicate of #61 ?

**Comment by vanderheyde** [comment]
> duplicate of #61 ?

I'm blind. Yes, thanks!
