### ISSUE TITLE
v1.5.7: Classifier process error

### ISSUE THREAD

**Issue by jakobroehrl** [marcelklehr/recognize#63]
Now I get this:
occ recognize:classify
Classifying photos of user xyz
Failed to classify images
Classifier process error

![image](https://user-images.githubusercontent.com/24530680/130488606-9a41742f-0634-48ca-9a41-ae14b1307cf9.png)

**Comment by LotusAxt** [comment]
Same here, recognize terminates without any error in the log:

> @:/$ docker exec nextcloud php -f /var/www/html/occ recognize:classify
> Classifying photos of user Admin
> Failed to classify images
> Classifier process error
>@:/$

But when enabling the app via console there comes one:

> @:/$ docker exec nextcloud php -f /var/www/html/occ app:enable recognize
> sh: 1: /var/www/html/apps/recognize/bin//node-v14.17.4-linux-arm64: Exec format error
> sh: 1: /var/www/html/apps/recognize/bin//node-v14.17.4-linux-arm64: Exec format error
> recognize 1.5.7 enabled

I don't know whether this error was already there in the previous versions, since this I use the web frontend for this stuff normally and this error doesn't show up there..

**Comment by vanderheyde** [comment]
Same issue here

log:

`[recognize] Warning: Classifier process output: internal/modules/cjs/loader.js:1131
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow_framework.so.2: file too short
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)


at 2021-08-23T17:31:16+00:00`
