### ISSUE TITLE
Classifier process errored

### ISSUE THREAD

**Issue by LotusAxt** [marcelklehr/recognize#65]
I installed v1.5.8 but the procces still fails without any usefull error message. :( 

```json
{
  "reqId": "b6Wn01s9daui30J6ezBX",
  "level": 2,
  "time": "2021-08-24T07:45:23+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "recognize",
  "method": "",
  "url": "--",
  "message": "Classifier process errored",
  "userAgent": "--",
  "version": "22.1.0.1",
  "id": "6124ac5f5bb41"
}
```json
{
  "reqId": "b6Wn01s9daui30J6ezBX",
  "level": 2,
  "time": "2021-08-24T07:45:23+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "recognize",
  "method": "",
  "url": "--",
  "message": "Classifier process error",
  "userAgent": "--",
  "version": "22.1.0.1",
  "id": "6124ac5f5bb0a"
}

**Comment by marcelklehr** [comment]
What's your Nextcloud version and system architecture?

**Comment by LotusAxt** [comment]
My Nextcloud runs in a Debian Buster Docker Container on a Synolgy DS918+, so it should be x64.
I tried both installations, first manually and when that didn't work I uninstalled the app in did a reinstall from the web UI.

**Comment by marcelklehr** [comment]
ok.

(The fact that you didn't run into https://github.com/marcelklehr/recognize/issues/52 when installing from the web UI is interesting...)

**Comment by marcelklehr** [comment]
There should be a warning-level log message before these two log messages, saying something like `Classifier process output: ...`

**Comment by LotusAxt** [comment]
Jep, also not very verbose :-/ 

```json
{
  "reqId": "b6Wn01s9daui30J6ezBX",
  "level": 2,
  "time": "2021-08-24T07:45:23+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "recognize",
  "method": "",
  "url": "--",
  "message": "Classifier process output: ",
  "userAgent": "--",
  "version": "22.1.0.1"
}
```

**Comment by LotusAxt** [comment]
Speaking of verbose: Is there a verbose logging parameter for the occ command?

**Comment by marcelklehr** [comment]
> Is there a verbose logging parameter for the occ command?

Not, currently. I agree that it could spit out more information again. The output was reduced by a refactor, but I'll take a look again.

> "Classifier process output: "

That would mean that the process fails silently :/ Can you try executing the classifier manually?

```
$ recognize/src/classifier_imagenet.js path/to/some/image-file.jpg
```

Thank you for sponsoring me, btw :heart:

**Comment by LotusAxt** [comment]
Sorry, I'm more of a c#/.Net guy and not familiar with node js. 😀
Is this call correct?

```
Merry@Isengard:/$ sudo -u http bin/node-v14.17.4-linux-x64 /volume1/Nextcloud/web/apps/recognize/src/classifier_imagenet.js /volume1/Nextcloud/data/Admin/files/Photos/Frog.jpg
Illegal instruction
```

**Comment by marcelklehr** [comment]
Mmh. seems correct. Can you try `sudo -u http bin/node-v14.17.4-linux-x64 --version`?

**Comment by LotusAxt** [comment]
Sorry, I deleted my former post as I realized I executed the command on the host machine and not within the Docker container. 😅

Within the container its:
```
#: sudo docker exec -i -u www-data nextcloud /var/www/html/apps/recognize/bin/node-v14.17.4-linux
-x64 /var/www/html/apps/recognize/src/classifier_imagenet.js /var/www/html/data/Admin/files/Photos/Frog.jpg
#: sudo docker exec -i -u www-data nextcloud /var/www/html/apps/recognize/bin/node-v14.17.4-linux-x64 --version
v14.17.4
#:
```

```
#: sudo docker exec -i -u www-data nextcloud lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       39 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               92
Model name:          Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
Stepping:            9
CPU MHz:             1501.000
CPU max MHz:         1501.0000
CPU min MHz:         800.0000
BogoMIPS:            2995.24
Virtualization:      VT-x
L1d cache:           24K
L1i cache:           32K
L2 cache:            1024K
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch intel_pt ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdseed smap clflushopt sha_ni xsaveopt xsavec xgetbv1 dtherm ida arat pln pts md_clear arch_capabilities
#:
```


For completeness the result on the host was:

When I execute it on the host the result is:
```
#: sudo -u http bin/node-v14.17.4-linux-x64 /volume1/Nextcloud/web/apps/recognize/src/classifier_imagenet.
js /volume1/Nextcloud/data/Admin/files/Photos/Frog.jpg
Illegal instruction
#: sudo -u http bin/node-v14.17.4-linux-x64 --version
v14.17.4
```

**Comment by marcelklehr** [comment]
It seems we have run into https://github.com/tensorflow/tfjs/issues/2631

**Comment by marcelklehr** [comment]
Two paths forward from here:

- I will probably add an option in the settings to force running the models in pure-js mode (slooow)
- More relevant for you: Install node.js and npm and run `rm -rf node_modules && npm install` in `apps/recognize` to have npm build libtensorflow according to your hardware specs.

**Comment by LotusAxt** [comment]
So, I installed node.js via nvm and ran the `rm -rf node_modules && npm install`. The good news: The two error messages in the Nextcloud Log are gone. The bad news: it still dosen't work. :( 
If I run `occ recognize:classify` the output is:

> Classifying photos of user Admin
> Failed to classify images
> Classifier process error

```json
{
  "reqId": "KBbgSJd7nbEibjgv1vJ5",
  "level": 2,
  "time": "2021-08-24T15:43:10+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "recognize",
  "method": "",
  "url": "--",
  "message": "Classifier process output: ",
  "userAgent": "--",
  "version": "22.1.0.1",
  "id": "6125138e97f97"
}
```

If I ran your test command `node recognize/src/classifier_imagenet.js path/to/some/image-file.jpg`:

> #$ /var/www/html/apps/recognize/bin/node-v14.17.4-linux-x64 /var/www/html/apps/recognize/src/classifier_imagenet.js /var/www/html/data/Admin/files/Photos/Frog.jpg
> Illegal instruction (core dumped)
> #$

I already tried `npm rebuild @tensorflow/tfjs-node --build-addon-from-source` but that also didn't help.

Any other Ideas?

**Comment by LotusAxt** [comment]
Okay, Thank you!

**Comment by spicemint** [comment]
now that i have been able to install (raspbian, nc 21.0.4) following [this](https://github.com/marcelklehr/recognize/issues/52#issuecomment-905304453)
when starting i get an error, nothing in logs:
`sudo -u www-data /usr/bin/php /var/www/nextcloud/occ recognize:classify
Classifying photos of user admin
Failed to classify images
Classifier process error`

**Comment by marcelklehr** [comment]
@spicemint Yep, raspi is arm, which does not work, yet. I'm on it.

**Comment by HelloKS** [comment]
I'm using J5040 (Goldmont Plus architecture), and same thing happens.
The source of problem is prebuilt libraries (`libtensorflow.so`, `libtensorflow_framework.so`) in `tfjs-node` library, which requires some specific CPU instructions which some CPUs don't have.

While I can try plain javascript option but I didn't want to because it will be painfully slow anyway. So here's how I did:
- Follow [Optional: Build optimal TensorFlow from source](https://github.com/tensorflow/tfjs/tree/master/tfjs-node#optional-build-optimal-tensorflow-from-source).
- During `./configure`, there will be `Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified` step. Enter `-march=goldmont`.
- Replace deps folder in recongnize folder to what you built.

Voila!
![result](https://user-images.githubusercontent.com/3853894/131234134-eb0ddfa8-c9ed-488a-9d0f-aed9e1ea7d37.jpg)

**Comment by marcelklehr** [comment]
This may also be a nice resource for downloading pre-built binaries for some architectures: https://github.com/kaufman-lab/build_tensorflow/releases (whl files are simply zip archives)

**Comment by debian-user-france1** [comment]
> ok.
> 
> (The fact that you didn't run into #52 when installing from the web UI is interesting...)

Yes, some versions worked. I also installed the LAST working version with Nextcloud to install
Smh it worked lol
Just deleted then BCS of bug and couldn't reinstall - made it without UI

**Comment by debian-user-france1** [comment]
> I'm using J5040 (Goldmont Plus architecture), and same thing happens.
> The source of problem is prebuilt libraries (`libtensorflow.so`, `libtensorflow_framework.so`) in `tfjs-node` library, which requires some specific CPU instructions which some CPUs don't have.
> 
> While I can try plain javascript option but I didn't want to because it will be painfully slow anyway. So here's how I did:
> 
>     * Follow [Optional: Build optimal TensorFlow from source](https://github.com/tensorflow/tfjs/tree/master/tfjs-node#optional-build-optimal-tensorflow-from-source).
> 
>     * During `./configure`, there will be `Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified` step. Enter `-march=goldmont`.
> 
>     * Replace deps folder in recongnize folder to what you built.
> 
> 
> Voila!
> ![result](https://user-images.githubusercontent.com/3853894/131234134-eb0ddfa8-c9ed-488a-9d0f-aed9e1ea7d37.jpg)

Does this improve any performance (I just installed it by Package and not built byself and I don't have to use JavaScript mode)

**Comment by marcelklehr** [comment]
I've forked that repository and setup a better pipeline to streamline this: https://github.com/marcelklehr/build_tensorflow/actions

**Comment by YouveGotMeowxy** [comment]
I'm getting a log full of these too. Using NC version 23.0.3 and the latest Recognize installed via the Apps page within NC itself.

![image](https://user-images.githubusercontent.com/39491297/160916494-50b55d3f-4169-4aaa-9e1c-aa2440b659e9.png)

**Comment by marcelklehr** [comment]
@YouveGotMeowxy As the title says, most likely, your CPU architecture is not supported by the standard tensorflow build. That means you have two options

1. Run in JS mode (Can be enabled in the admin settings for recognize)
2. Use a custom build of tensorflow for your architecture, you'll have to compile from source ([This repo](https://github.com/marcelklehr/build_tensorflow) may help, but I can't help with the details atm)

**Comment by YouveGotMeowxy** [comment]
> @YouveGotMeowxy As the title says, most likely, your CPU architecture is not supported by the standard tensorflow build. 

I'm just running it within an Ubuntu container on WSL (AMD Ryzen processor). Standard Tensorflow doesnt support that?

**Comment by YouveGotMeowxy** [comment]
Side question:

Any chance on helping to simplify our lives just "that much more" by adding simple buttons we can click to manually do these things? (buttons where the pink are). :-p

![image](https://user-images.githubusercontent.com/39491297/160920597-1d64d0c3-1eb0-4916-8afa-b4a6fe8580b0.png)

Save us from the gory, ugly command line. Copying and pasting commands, etc. lol

**Comment by marcelklehr** [comment]
> I'm just running it within an Ubuntu container on WSL (AMD Ryzen processor). Standard Tensorflow doesn't support that?

I have no idea if tensorflow supports your CPU. lscpu will tell you which instructions your CPU supports. Tensorflow needs avx and possibly avx512 or something like that. Don't remember off the top of my head. A different reason for the Permission denied error could be that it's actually about permissions. Recognize makes sure that all permissions are set on the node.js binary, but you can try whether executing `recognize/bin/node --version` works. If it does work, your CPU is to blame, if it does not, the installation failed.

> Also, are there any drawbacks to using the js mode? And if I use JS mode, will the OCC manual recognize still work?

JS mode is slower, but other than that should work fine.

**Comment by kbftech** [comment]
I installed node latest (18.2.0), npm 8.9.0, rebuilt tensorflow from source.
Running a VM (Linux KVM) with CPU model passthrough:
`
model name      : Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
[...]
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 cx16 pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave **avx** hypervisor lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid tsc_adjust xsaveopt arat umip md_clear arch_capabilities
`

Running the manual command seems to work fine:
`root@nextcloud:/var/www/html/nextcloud/apps/recognize# sudo -u www-data node /var/www/html/nextcloud/apps/recognize/src/classifier_imagenet.js  /var/www/html/nextcloud/data/WhateverPath/IMG.jpg
{
  className: 'banana',
  probability: 0.9136211276054382,
  rule: { threshold: 0.1, categories: [ 'fruit', 'food' ] }
}
{
  className: 'orange',
  probability: 0.0013075546594336629,
  rule: { label: 'fruit', threshold: 0.1, categories: [ 'food' ] }
}
`

But running the recognition doesn't (after listing 500 images and getting ready to process them):
`
Running array (
  0 => '',
  1 => '/var/www/html/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: sh: 1: exec: : Permission denied
Classifier process output: sh: 1: exec: : Permission denied
Failed to classify images
Classifier process error
`

Not sure what's wrong as afaik, all permissions *should* be fine.

**Comment by kbftech** [comment]
> > `0 => '',`
> 
> @kbftech You'll need to set the path to a node.js executable in the settings. The setting seems to have been lost.

Seems to work! Thanks :D  

Side note:
If you want to, try this: https://nextcloud.kfoster.tech/s/cdroSrwBejb2YDL/preview
If you register to Brave rewards, users like me can tip you. 1 bat is worth approximately 1USD afaik.

**Comment by kbftech** [comment]
> I'm getting a log full of these too. Using NC version 23.0.3 and the latest Recognize installed via the Apps page within NC itself.
> 
> ![image](https://user-images.githubusercontent.com/39491297/160916494-50b55d3f-4169-4aaa-9e1c-aa2440b659e9.png)
> 
> If I manually run: `occ recognize:classify-images`
> 
> It scrolls through many images found, finally ending with this:
> 
> ```
>   8073 => '/data/__groupfolders/1/Pets/Tucker/20210321_094827.jpg',
> )
> Running array (
>   0 => '',
>   1 => '/config/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
>   2 => '-',
> )
> sh: taskset: not found
> Classifier process output: sh: exec: line 1: : Permission denied
> 
> Classifier process output: sh: exec: line 1: : Permission denied
> 
> Failed to classify images
> Classifier process error
> ```
> 
> I'm using the Nextcloud Docker container, on Win 10 x64, WSL (Ubuntu containers).

Not sure if you fixed your issue, but you seem to have had the same as me (Node path is empty). Check @marcelklehr reply:


> > `0 => '',`
> 
> @kbftech You'll need to set the path to a node.js executable in the settings. The setting seems to have been lost.

**Comment by YouveGotMeowxy** [comment]
@kbftech 

TY for that. I added node `v14.19.0`, placed it's path in the recognize settings (`/usr/bin/node`) and then ran `occ recognize:classify-images` and it at least got me past that original error. Now I see all this though, lol:

> Running array (  0 => '/usr/bin/node',  1 => '/config/www/nextcloud/apps/recognize/src/classifier_imagenet.js',  2 => '-',)Classifier process output: Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)    at Module.load (internal/modules/cjs/loader.js:950:32)    at Function.Module._load (internal/modules/cjs/loader.js:790:12)    at Module.require (internal/modules/cjs/loader.js:974:19)    at require (internal/modules/cjs/helpers.js:101:18)    at Object.<anonymous> (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)    at Module._compile (internal/modules/cjs/loader.js:1085:14)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)    at Module.load (internal/modules/cjs/loader.js:950:32)    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {  code: 'ERR_DLOPEN_FAILED'}Classifier process output: Trying js-only modeClassifier process output: Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)    at Module.load (internal/modules/cjs/loader.js:950:32)    at Function.Module._load (internal/modules/cjs/loader.js:790:12)    at Module.require (internal/modules/cjs/loader.js:974:19)    at require (internal/modules/cjs/helpers.js:101:18)    at Object.<anonymous> (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)    at Module._compile (internal/modules/cjs/loader.js:1085:14)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)    at Module.load (internal/modules/cjs/loader.js:950:32)    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {  code: 'ERR_DLOPEN_FAILED'}Trying js-only modeClassifier process output: Error: Backend name 'tensorflow' not found in registry    at Engine.<anonymous> (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4238:35)    at step (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:123:27)    at Object.next (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:72:53)    at /config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:65:71    at new Promise (<anonymous>)    at __awaiter (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:51:12)    at Engine.setBackend (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4232:16)    at Object.setBackend (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:10577:19)    at Object.<anonymous> (/config/www/nextcloud/apps/recognize/src/classifier_imagenet.js:175:4)    at Module._compile (internal/modules/cjs/loader.js:1085:14)Classifier process output: Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)    at Module.load (internal/modules/cjs/loader.js:950:32)    at Function.Module._load (internal/modules/cjs/loader.js:790:12)    at Module.require (internal/modules/cjs/loader.js:974:19)    at require (internal/modules/cjs/helpers.js:101:18)    at Object.<anonymous> (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)    at Module._compile (internal/modules/cjs/loader.js:1085:14)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)    at Module.load (internal/modules/cjs/loader.js:950:32)    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {  code: 'ERR_DLOPEN_FAILED'}Trying js-only modeError: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)    at Module.load (internal/modules/cjs/loader.js:950:32)    at Function.Module._load (internal/modules/cjs/loader.js:790:12)    at Module.require (internal/modules/cjs/loader.js:974:19)    at require (internal/modules/cjs/helpers.js:101:18)    at Object.<anonymous> (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)    at Module._compile (internal/modules/cjs/loader.js:1085:14)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)    at Module.load (internal/modules/cjs/loader.js:950:32)    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {  code: 'ERR_DLOPEN_FAILED'}Trying js-only modeError: Backend name 'tensorflow' not found in registry    at Engine.<anonymous> (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4238:35)    at step (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:123:27)    at Object.next (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:72:53)    at /config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:65:71    at new Promise (<anonymous>)    at __awaiter (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:51:12)    at Engine.setBackend (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4232:16)    at Object.setBackend (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:10577:19)    at Object.<anonymous> (/config/www/nextcloud/apps/recognize/src/classifier_imagenet.js:175:4)    at Module._compile (internal/modules/cjs/loader.js:1085:14)


However, when I check the "Enable WASM mode" box and run it again, after awhile, it shows this (does this look right?):

![image](https://user-images.githubusercontent.com/39491297/168967994-4b4d34d6-ccd0-4216-9be6-8e81d69076e9.png)

**Comment by YouveGotMeowxy** [comment]
Side note: if this seems to be a common issue, and users have to install/add their own node.js (~550 Mbs) it might be better to just not install a shipped version of node and just note to users that they'll need to use an external node?

500 Mbs is heavy if it's unused, especially in a case like mine, where I'm running it in a container and it's usually best to keep containers as light as possible.

**Comment by kbftech** [comment]
@YouveGotMeowxy Wild guess: Your node_modules have not been generated correctly? Try this "again": 
`rm -rf node_modules && npm install`

FYI, I updated node and npm to latest before re-installing dependencies. I had a few errors saying my node version wasn't 14.whatever but it works fine nonetheless.

**Comment by YouveGotMeowxy** [comment]
@kbftech I appreciate all the help. 🌝

Maybe I'm installing it wrong? I'm running it in a container that's running Alpine, so I just do a `apk ass nodejs` and that's all.

I was under the impression that would install and setup everything on it's own?

**Comment by marcelklehr** [comment]
node.js should not be 500mb, afaik

**Comment by YouveGotMeowxy** [comment]
> node.js should not be 500mb, afaik

OK, you're right, I misread the startup log about the size. It's not 500 mb. Sorry about that. :)

**Comment by marcelklehr** [comment]
I'm not sure occ has an interactive shell, so I'm confused about what program you are running. The occ command used with recognize is located in the root of your nextcloud installation and can be run using

```shell
php occ recognize:classify-images
```

**Comment by YouveGotMeowxy** [comment]
> I'm not sure occ has an interactive shell, so I'm confused about what program you are running. The occ command used with recognize is located in the root of your nextcloud installation and can be run using

I'm using the OCC app that you can install from the Apps page within NC.

**Comment by marcelklehr** [comment]
Then [object Object] means there's a bug in the OCC app.

**Comment by YouveGotMeowxy** [comment]
@marcelklehr ok.

Side note: is it normal for the 'Checking CPU' waiting indicator on the settings page to never stop "waiting"? I've let it run all night and wake up to see it still waiting.
