### ISSUE TITLE
1.6.7: Error during installation "Cannot find module '../lib/main'"

### ISSUE THREAD

**Issue by linuxrrze** [marcelklehr/recognize#78]
Hi there,

I'm running into trouble when trying to install recognize app version 1.6.7 on Nextcloud 22.1.1:

```
{
  "reqId": "FzTWvN8HCrJwluRHJMmv",
  "level": 3,
  "time": "2021-08-31T15:33:03+02:00",
  "remoteAddr": "2001:a62:421:3401:f480:1ca7:fd7d:9ade",
  "user": "Administrator",
  "app": "no app in context",
  "method": "POST",
  "url": "/index.php/settings/apps/enable",
  "message": "Exception while executing repair step Install dependencies",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
  "version": "22.1.1.2",
  "exception": {
    "Exception": "Exception",
    "Message": "Failed to install Tensorflow.js: CPU-linux-3.8.0.tar.gz\nnode-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build\n/bin/sh: 1: node-pre-gyp: Permission denied",
    "Code": 0,
    "Trace": [
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/apps/recognize/lib/Migration/InstallDeps.php",
        "line": 81,
        "function": "runTfjsInstall",
        "class": "OCA\\Recognize\\Migration\\InstallDeps",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/Repair.php",
        "line": 123,
        "function": "run",
        "class": "OCA\\Recognize\\Migration\\InstallDeps",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/legacy/OC_App.php",
        "line": 1059,
        "function": "run",
        "class": "OC\\Repair",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/Installer.php",
        "line": 166,
        "function": "executeRepairSteps",
        "class": "OC_App",
        "type": "::"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/apps/settings/lib/Controller/AppSettingsController.php",
        "line": 447,
        "function": "installApp",
        "class": "OC\\Installer",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 217,
        "function": "enableApps",
        "class": "OCA\\Settings\\Controller\\AppSettingsController",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 126,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/AppFramework/App.php",
        "line": 156,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/Route/Router.php",
        "line": 301,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/base.php",
        "line": 1000,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/apps/recognize/lib/Migration/InstallDeps.php",
    "Line": 112,
    "CustomMessage": "Exception while executing repair step Install dependencies"
  }
}
```

I also tried to add execute permission during installation with a very ugly while loop, however this results in a different error:

```
{
  "reqId": "4UMOXxLciX0iuCBv3von",
  "level": 3,
  "time": "2021-08-31T15:36:46+02:00",
  "remoteAddr": "2001:a62:421:3401:f480:1ca7:fd7d:9ade",
  "user": "Administrator",
  "app": "no app in context",
  "method": "POST",
  "url": "/index.php/settings/apps/enable",
  "message": "Exception while executing repair step Install dependencies",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
  "version": "22.1.1.2",
  "exception": {
    "Exception": "Exception",
    "Message": "Failed to install Tensorflow.js: CPU-linux-3.8.0.tar.gz\nnode-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build\ninternal/modules/cjs/loader.js:892\n  throw err;\n  ^\n\nError: Cannot find module '../lib/main'\nRequire stack:\n- /mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/apps/recognize/node_modules/.bin/node-pre-gyp\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:745:27)\n    at Module.require (internal/modules/cjs/loader.js:961:19)\n    at require (internal/modules/cjs/helpers.js:92:18)\n    at Object.<anonymous> (/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/apps/recognize/node_modules/.bin/node-pre-gyp:4:1)\n    at Module._compile (internal/modules/cjs/loader.js:1072:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)\n    at Module.load (internal/modules/cjs/loader.js:937:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:778:12)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/apps/recognize/node_modules/.bin/node-pre-gyp'\n  ]\n}",
    "Code": 0,
    "Trace": [
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/apps/recognize/lib/Migration/InstallDeps.php",
        "line": 81,
        "function": "runTfjsInstall",
        "class": "OCA\\Recognize\\Migration\\InstallDeps",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/Repair.php",
        "line": 123,
        "function": "run",
        "class": "OCA\\Recognize\\Migration\\InstallDeps",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/legacy/OC_App.php",
        "line": 1059,
        "function": "run",
        "class": "OC\\Repair",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/Installer.php",
        "line": 157,
        "function": "executeRepairSteps",
        "class": "OC_App",
        "type": "::"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/apps/settings/lib/Controller/AppSettingsController.php",
        "line": 447,
        "function": "installApp",
        "class": "OC\\Installer",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 217,
        "function": "enableApps",
        "class": "OCA\\Settings\\Controller\\AppSettingsController",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 126,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/AppFramework/App.php",
        "line": 156,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/private/Route/Router.php",
        "line": 301,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/lib/base.php",
        "line": 1000,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/mnt/cowssd/web/apps/nextcloud/instances/prod/nextcloud-21.0.0/apps/recognize/lib/Migration/InstallDeps.php",
    "Line": 112,
    "CustomMessage": "Exception while executing repair step Install dependencies"
  }
}
```

Any idea?

**Comment by bonswouar** [comment]
@linuxrrze What OS is your Nextcloud's install running on?

**Comment by linuxrrze** [comment]
> @linuxrrze What OS is your Nextcloud's install running on?

Ubuntu 20.04 (x86_64)

**Comment by isaacolsen94** [comment]
Does it install now without errors on Ubuntu?

**Comment by metbosch** [comment]
I'm still facing the same issue when installing the 1.6.8 version from apps. I'm doing it on a rasspy4

**Comment by bonswouar** [comment]
There has been some similar problems on other projects but proposed solutions aren't really satisfying..
For example : https://github.com/jansmolders86/mediacenterjs/issues/191
Seems that installing `node-pre-gyp` globally worked for some, but would be much better to find out the origin of the issue!

**Comment by marcelklehr** [comment]
It's possible that the nextcloud installer resets the file mode upon app extraction. If that's the case, we need to set +x again on the affected files.

**Comment by bonswouar** [comment]
@marcelklehr yeah I can check, let's hope it's enough to fix the problem!

**Comment by isaacolsen94** [comment]
Any luck with the fix? Thank you guys for your hard work on this!!!

**Comment by marcelklehr** [comment]
The fix should be available within the hour.

**Comment by metbosch** [comment]
Still fail but with another error in my case:
```
{
"reqId":"---------",
"level":3,
"time":"2021-09-09T16:28:18+00:00",
"remoteAddr":"X.X.X.X",
"user":"XXX",
"app":"no app in context",
"method":"POST",
"url":"/index.php/settings/apps/enable",
"message":"Exception while executing repair step Install dependencies",
"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
"version":"22.1.1.2",
"exception":{
  "Exception":"Exception",
  "Message":"""
    Failed to install Tensorflow.js: CPU-linux-3.8.0.tar.gz
    node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
    internal/modules/cjs/loader.js:892
    throw err;
      ^
    Error: Cannot find module '../lib/main'
    Require stack:
     - /var/www/html/apps/recognize/node_modules/.bin/node-pre-gyp
       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
       at Function.Module._load (internal/modules/cjs/loader.js:745:27)
       at Module.require (internal/modules/cjs/loader.js:961:19)
       at require (internal/modules/cjs/helpers.js:92:18)
       at Object.<anonymous> (/var/www/html/apps/recognize/node_modules/.bin/node-pre-gyp:4:1)
       at Module._compile (internal/modules/cjs/loader.js:1072:14)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
       at Module.load (internal/modules/cjs/loader.js:937:32)
       at Function.Module._load (internal/modules/cjs/loader.js:778:12)
       at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
     code: 'MODULE_NOT_FOUND',
     requireStack: [ '/var/www/html/apps/recognize/node_modules/.bin/node-pre-gyp' ]
   }
  """,
  "Code":0,
  "Trace":[
    {"file":"/var/www/html/apps/recognize/lib/Migration/InstallDeps.php","line":83,"function":"runTfjsInstall","class":"OCA\\Recognize\\Migration\\InstallDeps","type":"->","args":["/var/www/html/apps/recognize/bin//node"]},
    {"file":"/var/www/html/lib/private/Repair.php","line":123,"function":"run","class":"OCA\\Recognize\\Migration\\InstallDeps","type":"->","args":[{"__class__":"OC\\Repair"}]},
    {"file":"/var/www/html/lib/private/legacy/OC_App.php","line":1059,"function":"run","class":"OC\\Repair","type":"->","args":[]},
    {"file":"/var/www/html/lib/private/Installer.php","line":157,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["recognize",{"step":"OCA\\Recognize\\Migration\\InstallDeps"}]},
    {"file":"/var/www/html/apps/settings/lib/Controller/AppSettingsController.php","line":447,"function":"installApp","class":"OC\\Installer","type":"->","args":["recognize"]},
    {"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["recognize"],[]]},
    {"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},
    {"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},
    {"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},
    {"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},
    {"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}
  ],
  "File":"/var/www/html/apps/recognize/lib/Migration/InstallDeps.php",
  "Line":114,
  "CustomMessage":"Exception while executing repair step Install dependencies"
},
"id":"613a362c90f1a"
}
```

If there is some readme about how to build/install by hand instead of using the appstore I can take a look on my system.

**Comment by bonswouar** [comment]
That's what I was worried about, I guess issue isn't fixed then..
@marcelklehr  `Error: Cannot find module '../lib/main'` is a weird one, npm unreliability is annoying! I'm open to suggestion on how to fix that

**Comment by marcelklehr** [comment]
Ah, my bad. This may work https://github.com/marcelklehr/recognize/pull/81

**Comment by marcelklehr** [comment]
Try v1.6.10

**Comment by metbosch** [comment]
I could install v1.6.10 without any error.
I'm running the initial `php occ recognize:classify -vvv` to see if models are correctly downloaded and some things are recognized :)
